// Common Union & Maharashtra state government department names,
// used to power autocomplete suggestions on the "Post a need" form.
export const departments: string[] = [
  // Maharashtra state departments
  'Dept. of Rural Development, Maharashtra',
  'Dept. of Urban Infrastructure, Maharashtra',
  'Dept. of Health & Family Welfare, Maharashtra',
  'Dept. of Agriculture, Maharashtra',
  'Dept. of Water Resources, Maharashtra',
  'Dept. of School Education, Maharashtra',
  'Dept. of Higher & Technical Education, Maharashtra',
  'Dept. of Skill Development & Entrepreneurship, Maharashtra',
  'Dept. of Industries, Maharashtra',
  'Dept. of Environment & Climate Change, Maharashtra',
  'Dept. of Housing, Maharashtra',
  'Dept. of Public Works, Maharashtra',
  'Dept. of Home, Maharashtra',
  'Dept. of Revenue & Forests, Maharashtra',
  'Dept. of Tourism & Cultural Affairs, Maharashtra',
  'Dept. of Cooperation, Marketing & Textiles, Maharashtra',
  'Dept. of Women & Child Development, Maharashtra',
  'Dept. of Social Justice & Special Assistance, Maharashtra',
  'Maharashtra State Innovation Society',
  'Maharashtra Pollution Control Board',

  // Union government departments (for cross-state / national pilots)
  'Ministry of Agriculture & Farmers Welfare',
  'Ministry of Health & Family Welfare',
  'Ministry of Education',
  'Ministry of Rural Development',
  'Ministry of Housing & Urban Affairs',
  'Ministry of New & Renewable Energy',
  'Ministry of Skill Development & Entrepreneurship',
  'Ministry of Electronics & Information Technology',
  'Ministry of Micro, Small & Medium Enterprises',
  'Ministry of Road Transport & Highways',
  'Ministry of Jal Shakti',
  'Ministry of Panchayati Raj',
  'Department for Promotion of Industry and Internal Trade (DPIIT)',
  'National Health Authority',
  'NITI Aayog',
  'Central Public Works Department (CPWD)',
];
